spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: secret
    url: jdbc:mysql://localhost:3306/rpidirector
    username: rpidirector
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    show-banner: false
  thymeleaf:
    cache: false

logging:
  level:
    jdbc: TRACE
    jdbc.resultsettable: DEBUG
    jdbc.sqltiming: TRACE
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  security:
    enabled: false
security:
  basic:
    enabled: false